export { default as SearchPage } from './SearchPage'
export { default as CoursesPage } from './CoursesPage'
export { default as CoursePage } from './CoursePage'
export { default as ErrorPage } from './ErrorPage'
export { default as AuthPage } from './AuthPage'
export { default as ProfessorPage } from './ProfessorPage'