export { default as AddCourseModal } from './AddCourseModal'
export { default as AddSectionModal } from './AddSectionModal'
export { default as Loader } from './Loader'
export { default as DeleteCourse } from './DeleteCourse'
export { default as SmallLoader } from './SmallLoader'
